name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Run_workspace_Tests:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.2.app && /usr/bin/xcodebuild -version
    - name: Install xcpretty
      run: sudo gem install xcpretty
    - name: Run unit tests
      run: xcodebuild test -scheme A-Commerce -workspace A-Commerce.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0' | xcpretty && exit ${PIPESTATUS[0]}