name: Build iOS Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Run_workspace_Tests:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
      
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    
    - uses: maierj/fastlane-action@v2.0.1
      with:
        lane: 'metrics'