name: Build iOS Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
      
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install xcpretty
      run: sudo gem install xcpretty
      
    - name: Run unit test
      run: make test
    
    - name: Run fastlane
      uses: maierj/fastlane-action@v2.0.1
      with:
        lane: 'metrics'
    
    - uses: actions/cache@v2
      id: restore-build
      with:
        path: ./*
        key: ${{ github.sha }}

  SonarCloud:
    needs: Test
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          